### ISSUE TITLE
Missing quotes on line 44

### ISSUE THREAD

**Issue by whoisroot** [sevsec/vt-scan#5]
You forgot to put `$FILE` between quotes on the `stat` command on line 44.

**Comment by sevsec** [comment]
Fixed! Thank you.

**Comment by whoisroot** [comment]
I should thank you!
You made my job a lot easier, now I don't have to open a browser in a VNC tunnelled via SSH to submit the suspicious files I analyse!

I even included some aliases on my [malware analysis functions](https://github.com/whoisroot/malware-analysis-functions) to use your script and a function to await for the results of the submitted file/URL/domain/IP.
