### ISSUE TITLE
script doesn't work

### ISSUE THREAD

**Issue by deviops-com** [sevsec/vt-scan#7]
Hello, 
I freshly installed vt-scan on my Rocky Linux 9.2, tried vt-scan and here is the message: 
```
./vt-scan.sh -k $API_KEY -f /root/breberky/0fuyham5.php
stat: cannot statx '""': No such file or directory
./vt-scan.sh: line 1: payload:allShortcutsEnabled:false: command not found
```

API key intentionally put behind variable.

UPDATE: 
Even version info doesn't work. 
`./vt-scan.sh -v
stat: cannot statx '""': No such file or directory
./vt-scan.sh: line 1: payload:allShortcutsEnabled:false: command not found
[root@small-webs-new vt-scan]# statx`

Thanks for fixing.

**Comment by sevsec** [comment]
Seems like an issue with your distro's stat command? Or there may be some odd protection in place preventing you from touching that file. Either way, I encourage you to troubleshoot the issue. 

I've made some efficiency adjustments to the script anyway, so it may work now.

**Comment by deviops-com** [comment]
works now without problems. Thanks
