### ISSUE TITLE
How to interprit the output

### ISSUE THREAD

**Issue by toddehb** [sevsec/vt-scan#8]
Hi, trying to use your script. Thanks for the work. When using it I get this output

`./vtscan.sh -k 5dede7ae08896a66575a1941f55166bb2573be -u www.heise.de
{
    "data": {
        "type": "analysis",
        "id": "u-0dfb6fac6de90bbba65fd1ca1685db7c022d662ed2d0368d304b2d45a453986e-1703844510",
        "links": {
            "self": "https://www.virustotal.com/api/v3/analyses/u-0dfb6fac6de90bbba65fd1ca1685db7c022d662ed2d0368d304b2d45a453986e-1703844510"
        }
    }
}`

I have no clue how to interprit this output. Any ideas. Exit code does not work. It's always 0. What if the url is malicious? What would the output then be?

**Comment by toddehb** [comment]
p.s.: I had to adjust the script for curl being POST not GET. GET is throwing an error.

**Comment by sevsec** [comment]
Good catch, the code has been updated and credited. (Also - are you sure you wanted URL scanning instead of domain scanning?)
