### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by wanggangroger** [sevsec/vt-scan#9]
{
    "error": {
        "code": "AuthenticationRequiredError",
        "message": "X-Apikey header is missing"
    }
}
how to fix it

**Comment by wanggangroger** [comment]
https://www.[virustotal.com/api/v3/analyses/ZmU4YjQwZDY5MGEzYTFlN2JlMTBjMjAxYjU2MTUyNGQ6MTczMzEyNTg2OA==

**Comment by sevsec** [comment]
You need to supply your VirusTotal API key.
